### ISSUE TITLE
Issue with taking a screenshot of a TF2 Hat: "Propaniac"

### ISSUE THREAD

**Issue by DrIsaacKleiner** [TF2CutContent/HLMVPlusPlus-IssueTracker#3]
The way it takes screenshots is by using a white and black background.
The white background makes the cosmetic invisible for some reason.

Hat info:
"item_name" "#TF_hwn2022_propaniac"
"image_inventory" "backpack/workshop/player/items/pyro/hwn2022_propaniac/hwn2022_propaniac"
"model_player" "models/workshop/player/items/pyro/hwn2022_propaniac/hwn2022_propaniac.mdl"

**Comment by gabrielwoj** [comment]
This seems to be applied on TF2 as well. I downloaded a map that has a white screen area and a green screen area (which I later replaced the texture with a black background). On the white screen area, the Propaniac's transparent-ish flames disappears completely:

![image](https://github.com/TF2CutContent/HLMVPlusPlus-IssueTracker/assets/13741779/412a5480-8d9c-4ca9-824b-81c674aaf19a)

But it looks fine on a black background:

![image](https://github.com/TF2CutContent/HLMVPlusPlus-IssueTracker/assets/13741779/1d55195e-d871-4a0a-8ce3-d1e7552c533c)

This doesn't look like it's a bug with HLMV or HLMV++, but rather on how the Source engine renders that sort of stuff. If there's a work around to it, I don't know.
